### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by sbuchok** [inrupt/solid-client-js#1777] opened 2022-11-25 18:00 UTC
I went to https://nodejs.org/en/download/
Installed latest version of node
ran npm install @inrupt/solid-client

got the following error:

npm : npm ERR! must provide string spec
At line:1 char:1
+ npm install @inrupt/solid-client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm ERR! must provide string spec:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Please provide a full list of steps for install in your documentation as what is there does not work. Not to mention your documentation doesn't have a link to node to install it and doesn't mention what version of node is supported. 

These are the instructions I used:

https://docs.inrupt.com/developer-tools/javascript/client-libraries/installation

**Comment by sbuchok** [comment] 2022-11-25 18:33
By the time I'm done, you guys are either:

A. Going to do what I originally requested and provide the JS files for everyone without the need for these ridiculous build chains (my opinion, not fact)
B. Have the best damned step by step install guide there is.

Either way, I'm not trying to fight against you, I am trying to make sure that this is easily available to as many Devs as possible.

**Comment by ThisIsMissEm** [comment] 2022-11-25 19:18
As replied here, you appear to be on Node.js 12.x which is *not* supported: https://github.com/inrupt/solid-client-js/issues/1775#issuecomment-1327747117

If you use a version of Node.js that is supported, such as 16.x, then you shouldn't face any issues. Furthermore, if you want help with npm install issues, we'll need the output of:

```
$ npx envinfo

$ npm install @inrupt/solid-client --verbose
```

`npx` is shipped with the recent LTS node.js releases. 

---

As for:

> By the time I'm done, you guys are either:

I will kindly remind you that this project has a code of conduct, this applies to everyone involved, even people opening issues: https://github.com/inrupt/solid-client-js/blob/main/CODE-OF-CONDUCT.md

**Comment by sbuchok** [comment] 2022-11-25 19:41
Can you please outline what part of the code of conduct I've gone against? I've offered to help with the install guide as it's missing steps. As for you saying that I appear to be on Node 12.x, I stated at the beginning of this ticket that I went and installed the latest version of Node. In the other ticket I stated that I was highjacking that ticket and instead would start a new ticket. 

There is no link to node in your documentation.
There is no indication on the installation page as to what version of node you support. 
All you have is a one liner that says to use npm install ... 
If you do this, you get the above error. 

This is the verbose output:

npm : npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
At line:1 char:1
+ npm install @inrupt/solid-client --verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm verb cli C:...\bin\npm-cli.js:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm info using npm@8.19.2
npm info using node@v18.12.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\steve\OneDrive\Projects\Solid\Solid\.npmrc Completed in 0ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:C:\Users\steve\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\steve\AppData\Roaming\npm\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 12ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm install @inrupt/solid-client
npm verb argv "install" "@inrupt/solid-client" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:display Completed in 5ms
npm verb logfile logs-max:10 dir:C:\Users\steve\AppData\Local\npm-cache\_logs
npm verb logfile C:\Users\steve\AppData\Local\npm-cache\_logs\2022-11-25T19_32_30_685Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 24ms
npm timing arborist:ctor Completed in 1ms
npm timing command:install Completed in 10ms
npm verb stack TypeError: must provide string spec
npm verb stack     at new Edge (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\edge.js:51:13)
npm verb stack     at [_loadDepType] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:887:9)
npm verb stack     at [Arborist.Node._loadDeps] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:864:23)
npm verb stack     at new Node (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:256:20)
npm verb stack     at [newNode] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:335:9)
npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:292:68
npm verb stack     at async [loadActual] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:137:25)
npm verb stack     at async Promise.all (index 0)
npm verb stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
npm verb stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:145:5)
npm verb cwd C:\Users\steve\OneDrive\Projects\Solid\Solid
npm verb Windows_NT 10.0.22621
npm verb node v18.12.1
npm verb npm  v8.19.2
npm ERR! must provide string spec
npm verb exit 1
npm timing npm Completed in 144ms
npm verb unfinished npm timer reify 1669404750816
npm verb unfinished npm timer reify:loadTrees 1669404750820
npm verb unfinished npm timer idealTree 1669404750821
npm verb unfinished npm timer idealTree:init 1669404750821
npm verb code 1

You guys are clearly able to build it and get the JS files, but for some reason, you aren't putting them up for people to use. I'm not sure why that is, but if you want the most number of people to use and adopt this, you need to cover the most area. JS files do this. But if you don't want to do it, I can't force you. So, I tried to use your documentation, but that doesn't work. So I have offered to help. I guess the above didn't come across that way. Basically, I'm offering to come up with a step by step guide on how to install, what versions, building it and getting the plain JS files from it if possible.

If you don't want help with any of that, please let me know and I can close off my tickets and sorry for the inconvenience.

**Comment by NSeydoux** [comment] 2022-11-25 20:23
You'll find the Node support policy on [this page](https://docs.inrupt.com/developer-tools/javascript/client-libraries/introduction/). We'll see if we can make this more obvious from the install page.

However, our documentation doesn't intend to be a NodeJS tutorial, as we only have limited resources so we have to keep a pretty focused scope. We have to assume some level of NodeJS familiarity from developers, so I can only recommend to look up a more general NodeJS tutorial before coming back to install these libraries. Unfortunately, a very granular install guide may not be the most appropriate solution, because the more details we put, the more assumptions we have to make about the underlying system, and basically there are much better npm tutorials online than whatever we would be able to write.

I understand your frustration, but to set appropriate expectations, we will not be changing our build chain to expose the transpiled JavaScript in the near future, as NPM tooling does a much better job at making this available than we would. Your feedback to the documentation is appreciated, and I'll double check the install. If I can't reproduce the problem, I'll close the issue.

**Comment by sbuchok** [comment] 2022-11-25 21:50
I would like to say that if this was C#, I'd use Nuget and would get the binaries. In this case, I'm supposed to use NPM, but, instead of getting the binaries, I have to get the source code and compile to get the binaries myself (the JS files). 

For reproducing the issue, use the latest version of Visual Studio and the latest version of Node. Using the Package Manager Console run "npm install @inrupt/solid-client"

I did nothing else.

My main frustration is that this is supposed to be a JavaScript library. By definition that should mean a .js file and that it can be referenced by a script tag or imported. This is not the case and you end up needing a tool chain. I get that you guys use it for you building of the library, but it shouldn't be needed to consume it.

I get you guys are going to change this, but this is a frustration I've had over and over again. I've had issues getting Aurelia, React, Angular and Node working in the past because of these tool chains and I'm getting tired of needing them when all I should need to do is point to a JS file and use it. 

Sorry about how this has come across, but I dying to try this stuff out and want to recommend it where I work as an auth alternative, however, if it relies on NPM, we won't be able to use it. This is why I need the plain JS files.

**Comment by ThisIsMissEm** [comment] 2022-11-28 16:44
As mentioned in the other issue #1775, node.js 18 isn't yet supported by the SDK, though I'm not sure why npm on windows would be giving you the error it is, you'd have to raise that with them.

I can see you're using node.js 18 from the logs:
``` 
npm verb Windows_NT 10.0.22621
npm verb node v18.12.1
npm verb npm v8.19.2
``` 

As mentioned in the other ticket we currently only support Node.js 16 and 14, as we need to do a lot of work to bring Node.js 18 features to the SDK, I'm going to close as a duplicate of #1775, but feel free to respond to this issue if you're having further install issues on Node.js 16

**Closed by ThisIsMissEm** 2022-11-28 16:44 UTC
Labels: bug

**Comment by sbuchok** [comment] 2022-11-28 17:32
I'm ok with this getting closed if you think that's the issue. This does still bring my point even more to light. JS should be thought of as the binary. You wouldn't ask people in a nuget package to get the source and compile it (C#). Same going for any other library. But for some reason, the frontend is different and we are expected to work in TypeScript and use NPM and Node and everything else rather than being given the binary (the JS files). I get that you guys won't be changing this any time soon (if ever), but in order to reach the most number of people I highly suggest talking and thinking about making the plain JS files available for those who don't want to use NPM, webpack... tool chains and want as few dependencies as possible.

Thanks and sorry I came off agressive. My comment about "Have the best damned step by step install guide there is." was meant as "I'm willing to help make this easier for everyone".

**Comment by ThisIsMissEm** [comment] 2022-11-28 18:39
@sbuchok on:
> You wouldn't ask people in a nuget package to get the source and compile it (C#). 

sorry, but that's just not what's happening here: you are just getting javascript files, the key part is that it's multiple files all targeting different module systems: commonjs, ECMAscript modules, and UMD. We also ship a bunch of `.d.ts` files that are the type definitions that Typescript uses. All this is just packages up into a tarball and delivered via npm. The nuget package manage is much the same: it downloads zip archives from a registry & extracts them.

The only case where compiling is needed is when there's missing platform features (different browsers) or where you're wanting to serve javascript more optimally by reducing the number of files loaded (which was really more of an issue before HTTP/2.0 was a thing).

In theory, you should just be able to use the .mjs files we distribute in our packages directly in the browser, but the problem you face is that the browser needs to find the other imported files, either from the same package or different packages.

I'm generally recommending people look at vite because it's one of the latest bundlers out there that supports ESM, and has hot code reloading and many other great features that make it a good development environment.
