### ISSUE TITLE
Error when using @inrupt/solid-client library with Pinia Store

### ISSUE THREAD

**Issue by qertis** [inrupt/solid-client-js#1924] opened 2023-04-05 13:07 UTC
### Bug description

I am unable to use the @inrupt/solid-client library together with Pinia Store. The page crashes with an unclear error message.

### To Reproduce

1, Open Quasar project

2. Create Pinia store and use it with the following code:

```typescript
import { defineStore } from 'pinia'
import { getDefaultSession } from '@inrupt/solid-client-authn-browser'
import { getPodUrlAll } from '@inrupt/solid-client'

interface State {
  webId: string
}

export default defineStore('pod', {
  state: (): State => ({
    webId: getDefaultSession().info.webId,
  }),
  actions: {
    async setResourceRootUrl() {
      const podsUrl = await getPodUrlAll(this.webId) as string[]
      return podsUrl[0]
    },
  },
})
```

3. Compile PWA
```
quasar build -m pwa
```

4. Open PWA
```
cd dist/pwa && python3 -m http.server --bind localhost 22870
```

### Expected result

The application loads without errors.

### Actual result

The application fails to load and crashes with the following error message:

```
[Error] TypeError: The superclass is not a constructor.
Module Code — profile.c6106db2.js:10073
```
![Screenshot 2023-04-05 at 15 56 01](https://user-images.githubusercontent.com/3893228/230088319-0809eb9c-a723-4564-91db-3369b660de60.png)

### Environment
```
"dependencies": {
    "quasar": "2.11.10",
    "typescript": "~5.0.3",
    "vue": "3.2.47",
    "pinia": "2.0.33"
}
```

**Comment by jeswr** [comment] 2023-04-05 23:58
Hi @quertis, it is difficult to reproduce the error with the information given. For instance I don't know what you mean by "open a quasar project"; and in step 3 I don't know how you're getting the global quasar command. Trying to run `npm run build` with the following package.json results in the error `Error Unknown command "build"`

```json
{
  "name": "pinia-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "quasar build -m pwa"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@inrupt/solid-client": "^1.26.0",
    "@inrupt/solid-client-authn-browser": "^1.14.0",
    "@quasar/cli": "^2.0.0",
    "pinia": "^2.0.33",
    "quasar": "^2.11.10",
    "typescript": "^5.0.3",
    "vue": "^3.2.47"
  }
}
```

---

Could you please create a minimal reproduction of your issue in a GitHub repository - with steps 3-4 in a build script. This repro should have all dependencies (including for CLI) in the package.json so we don't need to do any global installations to reproduce.

It would also be useful if you provide the full stack trace of the error you have provided (ideally with a source map so we know where the problem is coming from in the source code).

**Comment by qertis** [comment] 2023-04-06 08:12
> Hi @quertis, it is difficult to reproduce the error with the information given. For instance I don't know what you mean by "open a quasar project"; and in step 3 I don't know how you're getting the global quasar command. Trying to run `npm run build` with the following package.json results in the error `Error Unknown command "build"`
> 
> ```json
> {
>   "name": "pinia-test",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "build": "quasar build -m pwa"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "@inrupt/solid-client": "^1.26.0",
>     "@inrupt/solid-client-authn-browser": "^1.14.0",
>     "@quasar/cli": "^2.0.0",
>     "pinia": "^2.0.33",
>     "quasar": "^2.11.10",
>     "typescript": "^5.0.3",
>     "vue": "^3.2.47"
>   }
> }
> ```
> 
> Could you please create a minimal reproduction of your issue in a GitHub repository - with steps 3-4 in a build script. This repro should have all dependencies (including for CLI) in the package.json so we don't need to do any global installations to reproduce your observations.
> 
> It would also be useful if you provide the full stack trace of the error you have provided (ideally with a source map so we know where the problem is coming from in the source code).

Sure. You can observe this issue in the minimal project I created. You can check it out at https://github.com/qertis/solid-client.

**Comment by qertis** [comment] 2023-04-06 13:40
Also I did some research and came to the conclusion that your script does not work properly with the Vite deployment system. It is possible that you packaged the scripts incorrectly.

![Screenshot 2023-04-06 at 16 37 20](https://user-images.githubusercontent.com/3893228/230395368-b0f49a1a-d2f4-418a-9dec-6c46d318725e.png)

You can demonstrate it in another branch - https://github.com/qertis/solid-client/tree/target-esnext

Please check 
```
npm i
npm run pwa
```

**Comment by qertis** [comment] 2023-04-07 05:31
https://github.com/quasarframework/quasar/issues/15686

**Comment by jeswr** [comment] 2023-04-07 05:39
@qertis I take from the link above that this is an issue in quasar rather than solid-client, is that correct?

**Comment by qertis** [comment] 2023-04-07 08:23
@jeswr No, judging by the response in [the comment](https://github.com/quasarframework/quasar/issues/15686#issuecomment-1499990898), the issue lies specifically in the build of the @inrupt/solid-client library by the esbuild system.

**Comment by qertis** [comment] 2023-04-07 08:29
When I change the [esbuild target to es2022](https://esbuild.github.io/content-types/#javascript), I still see this error.

**Comment by jeswr** [comment] 2023-04-07 08:42
> Also I did some research and came to the conclusion that your script does not work properly with the Vite deployment system. It is possible that you packaged the scripts incorrectly.

The erroneous lines exist [here](https://github.com/nodejs/node/blob/0c769227ea1205d81f7de94f8d3568b72945fb58/lib/internal/errors.js#L1483-L1487) within the NodeJS codebase; so it seems more likely to be a problem with the behavior of esbuild; could you raise an issue with that team?

**Comment by qertis** [comment] 2023-04-07 09:03
Ok, sure. https://github.com/evanw/esbuild/issues/3044

**Comment by qertis** [comment] 2023-04-07 09:23
@jeswr Take a look at this example:
In the project https://github.com/qertis/solid-client/tree/terser, I created the `terser` branch. It is a different system from for Vite. Nevertheless, the error is being reproduced.

In fact, I can tell you that if you comment `getPodUrlAll` in code like this, everything works fine.

![](https://user-images.githubusercontent.com/3893228/230582789-c18d1cc2-a3e9-41e4-8785-4017c6ddcee5.png)

Therefore, the problem is with the @inrupt/solid-client library.

**Comment by qertis** [comment] 2023-04-07 11:16
> The problem here is circular dependencies in readable-stream not being transformed well in @rollup/plugin-commonjs@21 which is bundled in vite@2 which is a dependency of @quasar/app-vite. This was fixed in @rollup/plugin-commonjs@22 (the latest is 24 though).
> readable-stream is a dependency of n3, which is a dependency of @inrupt/solid-client which is the direct dependency of your project.

https://github.com/evanw/esbuild/issues/3044#issuecomment-1500156962

**Comment by jeswr** [comment] 2023-04-07 11:27
Closing as this seems to be an upstream issue based on that comment.

**Closed by jeswr** 2023-04-07 11:27 UTC
Labels: bug
